baseURL = 'https://charlottestormwater.com/'
canonifyURLs = true # ensures all URLs are absolute
languageCode = 'en-us'
title = 'Charlotte Stormwater'
enableRobotsTXT = true
enableGitInfo = true # for "lastmod" in RSS feed

[outputs]
home = ["HTML","JSON","RSS"]

[sitemap]
  changefreq = "weekly"
  filename   = "sitemap.xml"
  priority   = 0.5
  
[permalinks]
services = "/services/:slug/"
industries = "/industries/:slug/"
projects = "/projects/:slug/"

[taxonomies]
service = "services"
region = "regions"
asset = "assets"

[params.analytics]
provider = "gtag"          # "gtag" or "gtm"
ga4_id   = "G-7V5YR3TCLX"  # your GA4 ID
gtm_id   = ""              # e.g., "GTM-XXXXXXX" (leave blank for now)